# This contains params to be used by the stages to train or predict
# This contains params to be used by the stages to train or predict
AUGMENTATION:  True
IMAGE_SIZE: [224, 224, 3]
BATCH_SIZE: 64
EPOCHS: 1
CLASSES:  1
ACTIVATION: sigmoid
VALIDATION_SPLIT: 0.2
LOSS: binary_crossentropy
OPTIMIZER:  adam